---

- name: install package
  apt: pkg=emacs state=installed
  tags: emacs

- name: clone configuration from github
  sudo: no
  git: repo=https://github.com/kriben/.emacs.d.git dest=/home/{{ ansible_ssh_user }}/projects/.emacs.d update=yes recursive=yes

- name: remove current configuration
  file: path=/home/{{ ansible_ssh_user }}/.emacs.d state=absent
  
- name: install configuration
  shell: make install
  sudo: no
  args:
    chdir: /home/{{ ansible_ssh_user }}/projects/.emacs.d
    creates: /home/{{ ansible_ssh_user }}/.emacs.d
